export const CREATE_MODAL_SHOW = 'CREATE_MODAL_SHOW';
export const CREATE_MODAL_CLOSE = 'CREATE_MODAL_CLOSE';

export const OPEN_CARD_EXTENDED = 'OPEN_CARD_EXTENDED';
export const CLOSE_CARD_EXTENDED = 'CLOSE_CARD_EXTENDED';

export const ADD_NEW_CARD = 'ADD_NEW_CARD';
export const EDIT_CARD = 'EDIT_CARD';