export const CREATE_MODAL_SHOW = 'CREATE_MODAL_SHOW';
export const CREATE_MODAL_CLOSE = 'CREATE_MODAL_CLOSE';

export const TOGGLE_CARTE = 'TOGGLE_CARTE';
export const CLOSE_CARTE = 'CLOSE_CARTE';

export const OPEN_CARD_EXTENDED = 'OPEN_CARD_EXTENDED';
export const CLOSE_CARD_EXTENDED = 'CLOSE_CARD_EXTENDED';

export const ADD_NEW_CARD = 'ADD_NEW_CARD';
export const EDIT_CARD = 'EDIT_CARD';
export const CHANGE_ORDER = 'CHANGE_ORDER';

export const CHANGE_CURRENT_FOLDER = 'CHANGE_CURRENT_FOLDER';

export const ADD_FLD_OPEN = 'ADD_FLD_OPEN';
export const ADD_FLD_CLOSE = 'ADD_FLD_CLOSE';

export const ADD_NEW_FOLDER = 'ADD_NEW_FOLDER';